<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Computer Science')",
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Data Base')",
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'REST')",
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'SQL')",
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Web Development')",
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'IT')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'author1', 'author1')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'reader1', 'reader1')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'author2', 'author2')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'reader2', 'reader2')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'author3', 'author3')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'reader3', 'reader3')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'author4', 'author4')",
                "INSERT INTO " + schema + ".CUSTOMER (ID, IS_AUTHOR, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, TRUE, 2)",
                "INSERT INTO " + schema + ".CUSTOMER (ID, IS_AUTHOR, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, FALSE, 3)",
                "INSERT INTO " + schema + ".CUSTOMER (ID, IS_AUTHOR, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, TRUE, 4)",
                "INSERT INTO " + schema + ".CUSTOMER (ID, IS_AUTHOR, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, FALSE, 5)",
                "INSERT INTO " + schema + ".CUSTOMER (ID, IS_AUTHOR, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, TRUE, 6)",
                "INSERT INTO " + schema + ".CUSTOMER (ID, IS_AUTHOR, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, FALSE, 7)",
                "INSERT INTO " + schema + ".CUSTOMER (ID, IS_AUTHOR, CREDENTIALS_ID) VALUES (NEXT VALUE FOR CUSTOMER_GEN, TRUE, 8)"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
